name: monopoly_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.4
# dependencies:
#   flutter:
#     sdk: flutter
#   http: ^1.2.0
#   dio: ^5.4.1
#   retrofit: 4.0.2
#   json_annotation: 4.8.1
#   cupertino_icons: ^1.0.8

# dev_dependencies:
#   flutter_test:
#     sdk: flutter
#   flutter_lints: ^3.0.0
#   build_runner: 2.4.9
#   retrofit_generator: 8.0.0 
#   json_serializable: 6.7.1
dependencies:
  flutter:
    sdk: flutter
  dio: ^5.4.1
  retrofit: 4.1.0
  json_annotation: 4.8.1
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.8
  retrofit_generator: 8.1.0
  json_serializable: 6.7.1
flutter:
  uses-material-design: true
  assets:
    - assets/fondo.png
    - assets/icon/Advance.png
